[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "git-pilot"
version = "1.0.0"
description = "A GitHub MCP Server"
requires-python = ">=3.12,<4.0"
dependencies = [
    "fastmcp>=2.2.1",
]
